name: DonationEvents
version: '1.0.1'
main: org.dominator.donationEvents.DonationEvents
api-version: '1.21'
authors: [ Dominator ]
commands:
  lastDonations:
    description: Показати останні донати.
    usage: /lastDonats
    permission: donationEvents.view

  setAPIkey:
    description: Встановити АПІ ключ.
    usage: /setAPIkey
    permission: donationEvents.setAPIKey

  openSettingsMenu:
    description: Відкрити меню налаштування.
    usage: /openSettingsMenu
    permission: donationEvents.openSettingsMenu

  randEventSum:
    description: Випадковий івент із сумою N.
    usage: /randEventSum
    permission: donationEvents.randEventSum

  reloadEvents:
    description: Завантажити івенти із файлу.
    usage: /loadEvents
    permission: donationEvents.loadEvents

permissions:
  donationEvents:
    default: true

  donationEvents.openSettingsMenu:
    default: true

  donationEvents.randEventSum:
    default: true